app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: '@AppBundle/Controller/AdminController.php'
    type:     annotation
    prefix:   /admin

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
